spring:
  profiles:
    active: 
  application:
    name: basketballapi
  datasource:
    url: jdbc:mysql://localhost:3306/basketballapi
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
server:
  port: 8080